### ISSUE TITLE
function doOnNotAuthenticated should use $location properly

### ISSUE THREAD

**Issue by ocReaper** [Illniyar/visor#14]
The current function has a bad behavior, which I caused.
I had to use this function to change the default next url to whatever I needed, but if the url has a next parameter then it starts replacing (which actually works), but it leaves a comma (,) in the url :disappointed: 

The correct behavior instead of replacing the url via regex is to use the built in `$location.path()` and `$location.search()`.
The method then should look like:
```javascript
config.doOnNotAuthenticated = ["$location", "restrictedUrl", function ($location, restrictedUrl) {
  $location.path(config.loginRoute).search('next', restrictedUrl);
}];
```

Also it would be handy if we could change the next url manually whenever we needed, so please add it to the provider with:
```javascript
visor.addNextToUrl = function addNextToUrl(restrictedUrl){
  $location.search('next', restrictedUrl);
};
```

**Comment by Illniyar** [comment]
What do you mean by "The current function has a bad behavior, which I caused." , what was the bad behavior?
Can you give me an example of a Url that was added badly to the Next url and what was the result?

**Comment by Illniyar** [comment]
Also note that ```$location.path(config.loginRoute).search('next', restrictedUrl);``` isn't correct, since someone can have a config.loginRoute with search parameters or a hash.

**Comment by ocReaper** [comment]
I created an example for the issue. Maybe it could be much more simpler but I wanted to show you the full context.
http://codepen.io/ocReaper/pen/wMBBYz

here is the fix for that issue:
http://codepen.io/ocReaper/pen/wMBBQz

**Comment by Illniyar** [comment]
The only way I can see this situation happening in an actual application is if the ```loginRoute``` contains a ```next``` parameter by default.
Is that what happened?

I'll fix the issue that next doesn't get overridden but rather is added in addition (effectively creating an array in the parameter), but I just want to make sure that your underlying issue is fixed.
What was the scenario that originated this issue?

**Comment by ocReaper** [comment]
My default url is `/#/dashboard`. If the user is not authenticated than I throw him back to `/#/login`.
I had a login form on `/#/login` and after a successful authentication he will be navigated to a `/#/company-selector` url, which is not the default url where visor would navigate, so I add the next parameter to the url before calling `visor.setAuthenticated()`.
The problem appears when the user fails the login and the next parameter stays in the url.
At the second attempt he tries to login he succeeds but that comma appears in the url which is causing an error.

**Comment by Illniyar** [comment]
I've changed the ```config.doOnNotAuthenticated``` to use ```$location.url``` and ```$location.search``` .
This should fix similar issues.

From what I understand the issue that you had was because you used addNextToUrl directly and you solved it by just using ```$location.search``` instead, right? 
Since I'm now using ```$location.search``` directly, this should solve any theoretical issue.

**Comment by ocReaper** [comment]
Yes it solves my problem!
Thanks for the fix, and the fast response time!
