### ISSUE TITLE
startup visorProvider.authenticate

### ISSUE THREAD

**Issue by vptcnt** [Illniyar/visor#3]
Hello

I don't understand the idea to launch the visorProvider.authenticate when the page is loaded.
Specially with your example with an $http promise.

Could you please explain more the concept ? 

thanks

**Comment by Illniyar** [comment]
There are many applications where authenticating is required for every page so doing it on page load saves extra code (you can rely that authentication happened, even if the page isn't restricted) and can be a bit faster.

you can disable it with `visorProvider.authenticateOnStartup=false` .
