### ISSUE TITLE
login form and visorProvider.authenticate

### ISSUE THREAD

**Issue by vptcnt** [Illniyar/visor#4]
With a traditional login form (with username and password and a login button), when we click the "Login" button, should we call the visorProvider.authenticate (if we declare a $http promise) or should we manage the $http in the controller of the login form ?

Do you have an example ?

Thanks again

**Comment by Illniyar** [comment]
you can see the example site for ui-router: `http://illniyar.github.io/visor/sample/ui-router/#/home`
and the corresponding source code in `https://github.com/Illniyar/visor/tree/master/sample/ui-router`

you should never call visorProvider.authenticate directly, for login (which can be a different action/api then authentication) you do everything like you do in any other place, however once your done you call `visor.setAuthenticated(authInfo)` - which will automatically cause the url to redirect to the next url.

see the login controller in `https://github.com/Illniyar/visor/blob/master/sample/ui-router/app/app.js`
