### ISSUE TITLE
next param does not include previous path '/#'

### ISSUE THREAD

**Issue by alongal77** [Illniyar/visor#7]
if the path that was redirected to login screen is is http://www.example.com/#/mypage
the 'next' param is '/mypage' instead of '/#/mypage'

**Comment by Illniyar** [comment]
This isn't a bug, the next param is supposed to be '/mypage' - the path is the angular path.
When using hashbang mode angular knows how to translate it to '#/mypage' , and if you are using HTML5 history mode, then the path will actually be "http://www.example.com/mypage" .
If you've encountered an issue, you need to look into it and find the actual bug.
What's the actual scenario?

**Comment by alongal77** [comment]
We're trying to fix the bug where the first $location.url redirect after the login is not working.
In this case window.location solved the problem, but I understand it breaks things.
It caused only when redirecting to dashboard page. redirecting to other pages works.

**Comment by Illniyar** [comment]
does this happen when you go to the "dashboard" page directly (I.E. /dashboard) or when you are redirected from the index page (I.E. / ).
What breaks (or how does things break)?
What version of angular and ui-router are you using?

**Comment by alongal77** [comment]
angular: 1.3.2
angular-ui-router: 0.2.12
this happens when redirecting to /dashboard (i.e. - next param is /dashboard) and also when redirecting to '/' (next param is undefined)

**Comment by Illniyar** [comment]
any chance you can check the latest version to see if this happens?

**Comment by alongal77** [comment]
sure
