### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by DatenMetzgerX** [Illniyar/visor#8]
Might it be possible to package visor as NPM-Package.

**Comment by Illniyar** [comment]
Sure, You mean for browserify? can you give me an example of a client-side package that does what you want?
I usually use bower for client-side package management, so not really familiar with how to do it with npm.

**Comment by DatenMetzgerX** [comment]
Yes, we use webpack and only have npm dependencies (until now). 

It looks quite easy according to the [npm documentation](https://docs.npmjs.com/getting-started/publishing-npm-packages). 

I think the following things should be changed 

* remove bower install from postinstall (we do not want to install bower dependencies in npm environments)
* define angular as dependency (`npm install angular --save`)
* define the main file 

```js
{
  "name": "visor",
  "private": false,
  "author":"Illniyar",
  "main": "release/visor.js",
  ...
}
```
